# Custom Language File for Launcher Customizer

[ejs.app]
title = "MinePiece Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaWebSite = "https://minepiece.eu"
mediaTikTokUrl = "https://www.tiktok.com/@minepieces"
mediaTwitch = "https://www.twitch.tv/minepiece_serveur"
mediaYouTubeURL = "https://www.youtube.com/@MinePieceServeur"
mediaDiscordURL = "https://discord.gg/dRtjbzb"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "WELCOME TO MINEPIECE"
welcomeDescription = "Our mission is to recreate the universe of OnePiece in Minecraft."
welcomeDescCTA = "You are just a few clicks away from MinePiece."
